### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by GisVazquez14**

### CODE REVIEW

**Comment by GisVazquez14** [comment]
Algunos cambios en algunos títulos para mejor visualización.

**Comment by GisVazquez14** [comment]
Cambios en títulos para mejor visualización.

**Comment by carlism** [comment]
@GisVazquez14 I appreciate what you're trying to do here.  I'll run it by the teams and see if they like the look.  However, I think this sort of thing might be better achieved with a single css change rather than marking up all the headers.

**Comment by carlism** [comment]
@GisVazquez14  Thank you for your contribution!

**Pull request closed without merging**
