### PR TITLE
Update blog.html

### PR DESCRIPTION
**Pull request by shillasaebi**
updated blog with links to new material

### CODE REVIEW

**Comment by annania** [comment]
@shillasaebi line break HTML tag does not have a close tag. Please see example: https://www.w3schools.com/tags/tag_br.asp

**Comment by JohnRiv** [comment]
Since this is just content related, how about we merge this as-is and create an issue to switch to using proper `<li></li>` tags with the `<ul></ul>` that contains these? They may need a bit of CSS too.

**Comment by annania** [comment]
That works.

**Review by JohnRiv — APPROVED** [review]
I'll create an issue + PR to clean up the HTML

**Pull request merged**
