### PR TITLE
Added loader while fetching data

### PR DESCRIPTION
**Pull request by coderwassananmol**
#272

### CODE REVIEW

**Comment by coderwassananmol** [comment]
I am not able to sign the CLA via GitHub. Can you please send a scanned copy on my email?

**Comment by carlism** [comment]
I think cla-assistant.io has just been extremely slow.  I've noticed it loads eventually.  It'll show as a blank box for some time while it loads.

**Comment by coderwassananmol** [comment]
Even when I click on the button where it says "Sign in with GitHub to agree", it just loads and redirects me to the same page.

**Comment by coderwassananmol** [comment]
Meanwhile, can you please check the PR and let me know if any changes are required?

**Comment by carlism** [comment]
@coderwassananmol  This [comment](https://github.com/cla-assistant/cla-assistant/issues/492#issuecomment-539529784) refers to the issue you are having.  It's a problem with your account config and email address.

**Comment by coderwassananmol** [comment]
> @coderwassananmol This [comment](https://github.com/cla-assistant/cla-assistant/issues/492#issuecomment-539529784) refers to the issue you are having. It's a problem with your account config and email address.

Signed the CLA! :)

**Comment by carlism** [comment]
It's not bad as a loading indicator.  It looks like you put in code to remove the css class on load.  The numbers are filling in but it's not removing the loading treatment.  I've run the same lines in console and they work so I'm not sure if this is a weird timing issue or what.  It is, however, very repeatable.  The loading style never stops.

**Comment by coderwassananmol** [comment]
> It's not bad as a loading indicator. It looks like you put in code to remove the css class on load. The numbers are filling in but it's not removing the loading treatment. I've run the same lines in console and they work so I'm not sure if this is a weird timing issue or what. It is, however, very repeatable. The loading style never stops.

I am not able to reproduce it in my local. Can you please send a short video?
Also, are you testing it in a server or serving it directly from disk (file:///...)?

**Review by carlism — APPROVED** [review]

**Pull request merged**
